<Project>
  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <IsPluginProject
        Condition="'$(MSBuildProjectName)' != 'Landoria.SharedLib'
          and '$(MSBuildProjectName)' != 'DllMetadataVersion'">true</IsPluginProject>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsPluginProject)' == 'true'">
    <ILRepackTargetsFile>$(MSBuildThisFileDirectory)Landoria.SharedLib\ILRepack.targets</ILRepackTargetsFile>
    <HvAssembly>$(MSBuildThisFileDirectory)lib\HarmonyValidator.dll</HvAssembly>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPluginProject)' == 'true'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)Landoria.SharedLib\Landoria.SharedLib.csproj">
      <Private>false</Private>
    </ProjectReference>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'DllMetadataVersion'">
    <Reference Include="netstandard">
      <HintPath>$(ValheimGamePath)\valheim_Data\Managed\netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <Target Name="ValidateHarmonyTargets"
          AfterTargets="CoreCompile"
          BeforeTargets="CopyFilesToOutputDirectory;MergeLandoriaSharedLib"
          Condition="'$(IsPluginProject)' == 'true'">
    <PropertyGroup>
      <_HarmonyAssembly>@(IntermediateAssembly->'%(FullPath)')</_HarmonyAssembly>
      <_HvRefs>$(IntermediateOutputPath)harmony-references.txt</_HvRefs>
      <_HvCmd>dotnet &quot;$(HvAssembly)&quot;</_HvCmd>
      <_HvCmd>$(_HvCmd) &quot;$(_HarmonyAssembly)&quot;</_HvCmd>
      <_HvCmd>$(_HvCmd) &quot;$(_HvRefs)&quot;</_HvCmd>
    </PropertyGroup>
    <WriteLinesToFile File="$(_HvRefs)"
                      Lines="@(ReferencePath->'%(FullPath)')"
                      Overwrite="true" />
    <Exec Command="$(_HvCmd)" />
  </Target>
</Project>
